### ISSUE TITLE
MUIProgressDots - Boxes instead of dots

### ISSUE THREAD

**Issue by upiter** [mrfearless/ModernUI#9] opened 2018-09-25 22:07 UTC
# Instead of small dots huge boxes are drawn

## Intro

Image is better than words:
![muiprogressdots-001](https://user-images.githubusercontent.com/795353/46045634-e2a23780-c126-11e8-9d81-535c471f0794.png)
 
Problems:

- Animated blue box instead of animated small blue dots 
- Incorrect font mentioned in #8 
- Button at the bottom of dialog is incorrectly positioned (not seen completely)

## Functions

- `MUIProgressDotsCreate`
- `MUIProgressDotsSetProperty`
- `MUIButtonCreate`

## Sources

- Controls/ModernUI_ProgressDots/[ModernUI_ProgressDots.asm](Controls/ModernUI_ProgressDots/ModernUI_ProgressDots.asm)
- Examples/MUIProgressDotsTest/[MUIPDTest.asm](https://github.com/mrfearless/ModernUI/blob/master/Examples/MUIProgressDotsTest/MUIPDTest.asm)

**Comment by mrfearless** [comment] 2018-09-25 22:45
Thanks.

I can only assume the size of the Dots is a high value - so a safe range from 3 to 10 would be an option to prevent it looking huge and taking up loads of space as they cluster together to make a moving blob.

The font issue as mentioned hopefully will be fixed for the ModernUI_Text control soon.

Not sure why the button is incorrectly positioned - might be something to do with dialog units on different resolutions - Is the example used Example1 where the controls are created programmatically? or Example2 where the controls are created via the dialog resources? as this might help to narrow down where to look for the issue and understand it better.

**Comment by upiter** [comment] 2018-09-25 23:23
## MUIExample1

### No High DPI:
- Buttons are located too low

### High DPI:

- Dialog is big, but buttons and text are small and occupy smaller area (top left corner)

## MUIExample2

### No High DPI

- Buttons position seems to be OK
- When system resizes controls, they are positioned correctly
- In this example even font is OK (font creation line is commented)

### High DPI:

- Controls and texts are scaled by system
- Almost OK except very slow controls movement animation

**Comment by mrfearless** [comment] 2018-09-25 23:37
Ok, thanks for that info.
Yes from what I recall in Example 2 the separate panels have the fonts set and the MUIText controls inherit this font due to the flag style specified. And as the controls are created with the dialog manager, from the resources specified (and ModernUI controls are registered beforehand) they are created and windows handles the scaling as per CreateDialogParam, DialogBox, CreateWindowEx etc.

The first example the controls are created programmatically and thus the x, y co-ords are likely off for different resolutions and dpi (my own pc is 1920x1080) - so that explains the issue is related to creating the controls manually doesnt take into account the dpi settings.

Not sure about the animation, possibly effecting it due to the scaling, or some other thing that the Desktop Windows Manager (DWM) might be doing. If thats the case, then proper dpi support in the controls might eliminate this issue (as the dpi scaling isnt forced then as such)

**Comment by mrfearless** [comment] 2018-09-26 13:24
Might be the TimerQueue that is not as effective (http://omeg.pl/blog/2011/11/on-winapi-timers-and-their-resolution/) -  I have added Multimedia Timers to see if this changes anything. Also its possible to modify the following constants and adjust (and recompile) to see if it helps: 
```
DOTS_SHOW_INTERVAL  EQU 16 ; countdown til dot starts showing in animation
DOTS_TIME_INTERVAL  EQU 10 ; Milliseconds for timer firing, 10 seems fine, increasing this will slow down animations
```
Maybe the timeSetEvent will work better.

**Closed as completed** 2018-11-06 00:13 UTC
Labels: bug

**Comment by upiter** [comment] 2018-11-06 01:29
Current status:
- Animation is still slow
- Boxes instead of dots
